### ISSUE TITLE
Erroneous linting of plain text file

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kaste/SublimeLinter-contrib-codespell#1]
Thank you very much for creating this interface.

If I load a file that Sublime marks as plain text, it still gets linted by CodeSpell. That leads to such false positives as the following.

![image](https://github.com/user-attachments/assets/88c18be1-e8b0-45b8-a6c3-404ffa93da1c)

![image](https://github.com/user-attachments/assets/78a43dcb-fa46-4867-a25f-d56b40eab421)

CodeSpell 2.2.6 
SublimeText build 4183

**Comment by kaste** [comment]
I believe this to be the correct default. A spell checker should run on text files.  You can overrule, e.g.,

```
        "codespell": {
            "selector": "-text.plain",
            "styles": [
                {
                    "scope": "region.redish",
                    "annotation": "{msg}",
                    "phantom": ""
                }
            ]
        },
``` 

With this selector everything *but* `text.plain` should get assigned to the linter.

**Comment by LinuxOnTheDesktop** [comment]
I am unsure that _a simplified and designed-for-code spell checker_ should run on text files.

Thanks for the override. However, where does it go? I find that on my system (and perhaps due to user error) I have a `.codespellrc` file and a `codespellrc` file (_sic_).

**Comment by kaste** [comment]
Such overrides go in to the SublimeLinter settings (`Preferences: SublimeLinter Settings`) or the project/view settings (https://www.sublimelinter.com/en/latest/settings.html).

**Comment by kaste** [comment]
Okay, then I close.  🦞

**Comment by LinuxOnTheDesktop** [comment]
> Okay, then I close.

I did write:

> I am unsure that a simplified and designed-for-code spell checker should run on text files.

But of course the decision is yours, and having an easy-ish work-around means that the matter is not critical.

**Comment by kaste** [comment]
codespell is not, besides its name, designed around code.  It is used for markdown, documentation.  

The specific design of codespell is that it doesn't rely on dictionaries that basically define or tell how a word must be spelled.  With that traditional design, users usually have to train the speller a lot, and e.g. your "sav" would have been squiggled too.   The design of codespell is that its "dictionary" holds typical misspellings that typically happen when typing on a keyboard, but probably wouldn't happen when writing with a pen-paper.

**Comment by LinuxOnTheDesktop** [comment]
Aha. Right. Yet, how often do markdown and other documentation formats comprises files that Sublime marks as plain text?

**Comment by kaste** [comment]
I write my notes in plain text.  ascii.  However, I have the above selector, t.i. `-text.plain`, because codespell only understands English.   If we make a poll, we had an *opinion* based on facts, so it would be just an arbitrary choice.  Technically, codespell works with any text/unicode file, and the default selector just reflects that.
